Feat/get raw sql
sequelize/sequelize pull request #11881
Opened 2020-01-27 16:36 UTC by seromenho

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Implements https://github.com/sequelize/sequelize/issues/2325

I'll come back to this and improve the PR description and add some tests if someone confirms this direction.
Thanks

2020-03-06 12:22 UTC, jdgriffith commented
This would be a great addition that our organization would use immediately. Any chance we can get feedback on whether this is a good approach?

2021-05-18 10:12 UTC, dleo9307 approved these changes

2021-06-03 15:40 UTC, tjwhitfield-lilly commented
@dleo9307 What is the timeframe on this getting merged / released?

2021-07-09 04:17 UTC, baweinbe commented on src/dialects/abstract/query-interface.js
> +    const query = this.QueryGenerator.selectQuery(tableName, options, model);
looks like this should be `const query = this.queryGenerator.selectQuery(tableName, options, model);`

2021-11-17 09:37 UTC, viraldudhat approved these changes

2021-11-17 09:48 UTC, jdgriffith commented
Do I dare hope this is about to make it into sequelize?! 😍

2021-11-18 19:00 UTC, sdepold commented
if it is WIP: Can we maybe convert it into a draft PR?

2021-11-18 19:02 UTC, sdepold commented
fwiw: I just rebased. main is now including some bits and pieces about typescript. it shouldn't make a huge diff

2021-11-21 14:50 UTC, Keimeno requested changes
Thanks for your contribution @seromenho, and sorry for the late response!

I've marked two things that I would change about this PR.

There's also a problem inside our `lib/model.js`, where we make use of the `select` method. https://github.com/sequelize/sequelize/blob/407137822a62897f7366980acd7eeceb443601b9/lib/model.js#L1754-L1770

We have a problem here, because our result is processed further, we will have to check for these scenarios as well.

Also, I'm unsure if we should limit this option for `findAndCountAll`, `findAll` and `findOne` queries, but it might as well make sense to separate this into multiple PRs

2021-11-21 14:50 UTC, Keimeno commented on lib/hooks.js
> +    if (hookArgs[0] && typeof hookArgs[0] === 'object' && hookArgs[0].getRawSql) {
Hooks can also modify the resulting query, such as `beforeFind`. I think it's best if we extend the `hookTypes` object, and add a new option to each hook that we want to run, when getting the raw SQL query

2021-11-21 14:50 UTC, Keimeno commented on lib/dialects/abstract/query-interface.js
> +    if (options.getRawSql) {
I'm unsure if `getRawSql` is the best name for this option, I would probably go with something like `queryOnly`, `getQuery`, `query` or something else.

2022-04-07 10:24 UTC, ephys commented
One note I have about this PR is that we should avoid having different return types for our functions. It makes typing them and using them with TypeScript much more complicated.

Instead, let's add a new method that does this. Maybe `Model.getFindQuery`, `Model.findAll.getQuery()`, or let's keep it as a method on the Query Builder? #394

2022-04-07 14:54 UTC, piotr-pawlowski commented
When do you plan to merge this PR? We really need that feature.

2022-12-08 17:39 UTC, closed without merging

2024-04-26 00:47 UTC, cr0mbly commented
I know there was talks about making the `QueryGenerator` public, but it's been a few years. If this isn't going to be the case we can institute the above PR. Would love to use this natively.

2024-04-26 02:16 UTC, jdgriffith commented
A part of me is sad to look back and see my first comment on this thread was four years ago. 

I think it's worth merging this PR, assuming it's ready or can be modified easily, as a stop gap until new features or v7 arrives.

2024-04-26 15:12 UTC, Nick-Riggs commented
I've needed this for years for different projects, and I've always monkey-patched it. It may not cover every case, but something to the effect of:

```
    const realQuery = sequelize.query.bind(sequelize);

    sequelize.query = async function (sql: string, options: QueryOptions) {
        if (options?.returnSqlOnly) {
            return sql;
        }

        return realQuery(sql, options);
    }
```

I hope to see it in the framework proper someday as well.

2024-04-26 15:51 UTC, jdgriffith commented
@Nick-Riggs Our team has had to do something similar because we have a dynamic query layer based on the sequelize ORM.

2024-05-07 17:47 UTC, cr0mbly commented
@ephys this seems like a pretty big want/need from the community, are we able to look at this again?

I Just note again most ORMs I've dealt with have offered easy exposure of the SQL they're building within the ORM builder itself, it'd be nice if sequlize kept to that convention:

```
### Rails
Model.all.to_sql
>>> "SELECT `models`.* FROM `models`" 

### Django
Model.objects.all().query()
>>> "SELECT `models`.* FROM `models`"
```