fix(types): Allow transaction to be null in Transactionable interface (#13092).
sequelize/sequelize pull request #13093
Opened 2021-03-11 16:08 UTC by yjwong

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions? (typing issue)
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

When using TypeScript with `strictNullChecks` enabled, we cannot pass `null` to `transaction`, but this is actually allowed and used to execute in a non-transaction context when in an auto-transaction block.

Closes #13092.

2021-03-12 18:14 UTC, papb approved these changes

2021-03-12 18:14 UTC, papb commented
Hello! Thanks!

2021-03-12 18:15 UTC, papb requested changes
Actually, can you please add a typings test [here](https://github.com/sequelize/sequelize/blob/main/types/test/transaction.ts) for this?

2021-03-12 18:21 UTC, papb commented
> I wish for this change to also be backported to v5. How do I go about doing that?

You create a new branch off the `v5` branch, do the same changes you did here (including a test, please), and open a new pull request selecting `v5` as the target branch (instead of `main`). And write something like this in its description:

> *This PR is a backport of #13093 into v5*

2021-03-13 04:04 UTC, yjwong commented
I tried running `npm run test-typings` locally but got this output:

```
> sequelize@0.0.0-development test-typings /home/yjwong/Documents/sequelize
> tsc -b types/tsconfig.json && tsc -b types/test/tsconfig.json

types/test/define.ts:30:43 - error TS2511: Cannot create an instance of an abstract class.

30   expectTypeOf<UserModel>().toMatchTypeOf(new User());
                                             ~~~~~~~~~~

types/test/define.ts:63:50 - error TS2511: Cannot create an instance of an abstract class.

63   expectTypeOf<UntypedUserModel>().toMatchTypeOf(new UntypedUser());
                                                    ~~~~~~~~~~~~~~~~~


Found 2 errors.
```

These errors doesn't seem to be related to the tests I added.

2021-03-13 05:12 UTC, papb approved these changes

2021-03-13 05:13 UTC, papb commented
@yjwong Hmm, that's weird, but since tests are passing on GitHub Actions, don't worry about it. Just in case, can you confirm what is your TS local version?

2021-03-13 05:23 UTC, merged

2021-03-13 08:07 UTC, yjwong commented
@papb I found out why, I manually installed TypeScript 4.1.x using `npm install --save-dev typescript@~4.1` and it ran without error. Seems like it's more of an issue with TypeScript 4.2.x.