fix(mariadb): Process JSON fields only if actually requested (#13027 & #12583
sequelize/sequelize pull request #13273
Opened 2021-05-13 21:45 UTC by das-peter

Adding JSON fields to rows regardless if requested or not breaks AbstractQuery::_groupJoinData() for example.

Fixes #13027 & #12583

2021-05-13 21:49 UTC, das-peter commented
Cross linking issue that sent me on this debugging journey https://github.com/ForestAdmin/forest-express-sequelize/issues/723

2021-05-26 20:40 UTC, AllAwesome497 requested changes
Please update this pull request to match the template and / or match [contributing guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#pull-requests). 

I'm not sure what the issue is.

2021-05-27 12:29 UTC, das-peter commented
@AllAwesome497 Thanks for the feedback. Updated the description. 
Management summary:
MariaDB JSON field processing always adds JSON fields to result-set, even if fields weren't requested.
This breaks stuff that's working based on result-set structure.
Solution: Only process JSON field if it was requested  / part of the result-set.

2021-05-27 19:37 UTC, AllAwesome497 commented
> @AllAwesome497 Thanks for the feedback. Updated the description.
> Management summary:
> MariaDB JSON field processing always adds JSON fields to result-set, even if fields weren't requested.
> This breaks stuff that's working based on result-set structure.
> Solution: Only process JSON field if it was requested / part of the result-set.

I'm still not sure what the issue is, can you give more info like:
- When / why this would be an issue
- An example of the query that you see this issue in
- What your result was
- What the result you expected is
- An example model where this issue comes up in.

2021-05-27 20:48 UTC, das-peter commented
I sincerely am not sure if this now all about satisfying bureaucracy :|

However, here's a minimal example based on pseudo code:
Schema:
```
  const attributes = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    whatever: {
      type: DataTypes.STRING,
      allowNull: false
    },
    evilJSONField: {
      type: DataTypes.JSON,
      allowNull: false,
      parse: true
    }
  };
  sequelize.define('Demos', attributes, { timestamps: true });
```

Query:
```
  await db.demo.sync({ alter: true });
  await db.demo.truncate({ logging: console.log });
  await db.demo.create({ whatever: 'foo', evilJSONField: JSON.stringify(['random', 'data']) });
  const records = await db.demo.findAll({ attributes: ['id', 'whatever'], raw: true });
  console.log(records);
```
This would trigger following select query:  ` SELECT id, whatever FROM Demos AS Demos;`

And it will return:
```
[ { id: 1, whatever: 'foo', evilJSONField: null } ]
```

See that `evilJSONField`? That's bad. Because it was not requested, it shouldn't be there. 
And it's presence doesn't just violate the expectation you'd have from the generated query or the promise of `raw: true` to show only what the query returns, but that unexpected field will break the processing in  `AbstractQuery::_groupJoinData()` and probably other locations.

2021-05-30 02:21 UTC, AllAwesome497 approved these changes
I edited your comment to use [syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).  Thanks for adding code samples + the clarification.


Looks fine once linting is fixed.  Can you also add a test for this to prevent regression?

2021-05-30 02:47 UTC, AllAwesome497 commented on lib/dialects/mariadb/query.js
> +          if(row[modelField.fieldName] !== undefined) {
oh also: it looks like this doesn't fix #13027.

for that you should probably do something like:
```suggestion
          if(typeof row[modelField.fieldName] === 'string') {
```

2021-11-02 00:07 UTC, closed without merging