fix(typings): update returns union of types
sequelize/sequelize pull request #14155
Opened 2022-02-23 22:47 UTC by guyellis

### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

As per the docs in the type I've updated the type.

A few lines above the change is a description where the update() method can return 2 types. I added the 2nd type.

2022-02-23 23:07 UTC, guyellis commented on src/model.d.ts
> +  ): Promise<[number] | [number, M[]]>;
A few lines above this the docs for this method say:

> The promise returns an array with one or two elements...

2022-02-23 23:08 UTC, guyellis commented on src/model.d.ts
> +  ): Promise<[number] | [number, M[]]>;
And I can confirm that the functionality is accurate based on the docs and that the types didn't match the return type which is why I'm submitting this PR.

2022-02-24 01:07 UTC, guyellis commented
Failing test looks like a random issue unrelated to this PR:

```
  1 failing

  1) [SQLITE] Transaction
       fails with SQLITE_BUSY when retry.match is changed:
     AssertionError: expected promise to be rejected with an error including 'SQLITE_BUSY: database is locked' but it was fulfilled with [ undefined, undefined ]
      at assertIfNotNegated (node_modules/chai-as-promised/lib/chai-as-promised.js:68:19)
      at /home/runner/work/sequelize/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:183:17
      at async Context.<anonymous> (test/integration/transaction.test.js:739:9)
```

2022-02-24 10:25 UTC, ephys requested changes
I think we could handle this like `Model.count`: have two method signatures:
- one with option.returning set to true that returns `[affectedCount: number, affectedRows: M[]]`
- one without option.returning (or set to false) that returns `[affectedCount: number]`

2022-02-24 10:25 UTC, ephys commented on src/model.d.ts
> +  ): Promise<[number] | [number, M[]]>;
Suggestion to follow the format that's used in https://github.com/sequelize/sequelize/pull/14145

```suggestion
  ): Promise<[affectedCount: number, affectedRows?: M[]]>;
```

2022-02-24 10:30 UTC, ephys commented
Also you're right, the sqlite issue is something that started happening randomly recently but unrelated to your PR

2022-02-24 13:51 UTC, guyellis commented
> I think we could handle this like `Model.count`: have two method signatures:
> 
> * one with option.returning set to true that returns `[affectedCount: number, affectedRows: M[]]`
> * one without option.returning (or set to false) that returns `[affectedCount: number]`

That was a great idea. Thank you! I've made the changes and pushed them. LMK what you think. Thanks.

2022-02-24 14:28 UTC, ephys commented on src/model.d.ts
> +  ): Promise<[affectedCount: number, affectedRows?: M[]]>;
I think as you split the two signatures, the new signature should be:

```suggestion
  ): Promise<[affectedCount: number, affectedRows: M[]]>;
```

2022-02-24 16:03 UTC, ephys approved these changes
Thanks, I think we're good to go :)
Merging another PR first then I'll update & merge this one

2022-02-24 16:09 UTC, guyellis commented
> Thanks, I think we're good to go :) Merging [another PR](https://github.com/sequelize/sequelize/pull/14151) first then I'll update & merge this one

Thank you for doing this! You are awesome! :trophy:

2022-02-24 17:26 UTC, merged

2022-03-01 06:26 UTC, Kessa713 commented
There's an issue with this in reference to the documentation and current functionality for `returning: (keyof TAttributes)[]` as listed [here](https://sequelize.org/v6/class/src/model.js~Model.html#static-method-update)
This breaks existing type checks when updating to v6.17.0

2022-03-04 14:01 UTC, ruiaraujolink commented
Hi, this PR create a problem, when I pass an array of attributes this happens
<img width="926" alt="Screenshot 2022-03-04 at 13 58 40" src="https://user-images.githubusercontent.com/87080444/156776720-28dec14c-2726-4412-819a-f79a8b2b34fb.png">

2022-03-04 14:37 UTC, WikiRik commented
> Hi, this PR create a problem, when I pass an array of attributes this happens
> <img width="926" alt="Screenshot 2022-03-04 at 13 58 40" src="https://user-images.githubusercontent.com/87080444/156776720-28dec14c-2726-4412-819a-f79a8b2b34fb.png">
>  

Hi! This should be fixed with #14184 right? That PR will be reviewed soon and then we will release a new version

2022-03-04 15:29 UTC, ruiaraujolink commented
> > Hi, this PR create a problem, when I pass an array of attributes this happens
> > <img alt="Screenshot 2022-03-04 at 13 58 40" width="926" src="https://user-images.githubusercontent.com/87080444/156776720-28dec14c-2726-4412-819a-f79a8b2b34fb.png">
> 
> Hi! This should be fixed with #14184 right? That PR will be reviewed soon and then we will release a new version

I think so, thanks.