fix(mssql): stop to automatically add `order by` when there is a `group`
sequelize/sequelize pull request #14194
Opened 2022-03-03 18:10 UTC by arnaud-moncel

### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [X] Have you added new tests to prevent regressions?
- [X] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Should fix #14185 

Should not auto adding `order by` clause when a `group` option is provided. Should avoid sql error
`[column] is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.`

2022-03-04 09:25 UTC, ephys commented
Thank you for the PR!

Instead of the unit test that specifically tests `addLimitAndOffset`, I'd rather have a test in `test/unit/sql/select.test.js` that tests a minimal reproducible findAll similar to what you have in https://github.com/sequelize/sequelize/issues/14185

2022-03-07 09:56 UTC, arnaud-moncel commented
I don't understand why some tests are failing 🤷,
I think the modifications I made should not impact them, I'm right?

2022-03-07 09:57 UTC, ephys commented
You're targetting the v6 branch which has some failing tests with the newer docker images, but I don't think it's related to your PR

2022-03-08 10:17 UTC, arnaud-moncel commented
Hi 👋 I do it like this at the beginning. And one integration tests fail. 👇

https://github.com/sequelize/sequelize/blob/e974e202ca755a008f450c88123fc166a5497bb2/test/integration/model/findAll/groupedLimit.test.js#L118-L138

I deep dive in the test and, I make test on my end to understand what happens. And the result is pretty strange 😅.

I extracted the subquery created by the queryGenerator and I executed it manually.
The first attempt without limit / offset:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/22832474/157214812-2f92b8eb-03c1-458b-b603-bbc224d7b79c.png">

We are agree about, if i add limit 3 the result should be `id: [3, 4, 5]`.
But in reality the result is:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/22832474/157215308-b6eb005e-9a1c-46cf-a7f8-719402d888d3.png">

IMO that’s why there is a "Flaky" test and that’s why the code is like this.

I don’t know if it clear.

2022-03-11 08:35 UTC, arnaud-moncel commented
So what do we do? 😅

2022-03-11 22:01 UTC, ephys commented
I would be consider the test to be at fault here. 
The ORDER BY provided in that test is not stable, multiple people have the same age.

I think it's the responsibility of the developer to provide a stable ORDER BY. Trying to fix their ORDER BY ourselves is going to be incompatible with aggregation functions and since users can use literals, it's not possible for us to determine whether an aggregation function is used to skip 'fixing' the order by.

I think the most we should do is provide a default ORDER BY if one is needed and none was provided. The rest is up to the developer :)

I would change the test to

```typescript
order: [ 
  Sequelize.fn('ABS', Sequelize.col('age')),
  'id',
], 
```

ping @sequelize/maintainers if someone wants to weigh in on this issue

2022-03-22 09:53 UTC, ephys commented
Oh no I've just noticed you opened this PR against v6.
This is very likely to be a breaking change, we can't include it in v6. Could you add it to `main` instead?

2022-03-22 11:20 UTC, ephys commented
> I must re do in another PR targeting v6 the first version of my fix?

I think it may be best. Let's have a temporary workaround in v6 to resolve your issue, and a proper fix in v7

2022-06-11 09:14 UTC, WikiRik commented
@arnaud-moncel can you resolve the conflicts? Then we'll take another look at this

2022-07-03 10:18 UTC, ephys requested changes
The unit tests are failing, can you re-request a review once the tests are green?

2023-03-24 14:15 UTC, evanrittenhouse submitted a review, later dismissed

2023-05-08 00:10 UTC, closed without merging