docs(scopes): update manual documentation on where scope merging
sequelize/sequelize pull request #14202
Opened 2022-03-06 11:09 UTC by EtienneTurc

This pr updates the manual documentation when merging multiple where scopes. 

The described changes have been made in:
- https://github.com/sequelize/sequelize/pull/14152

Note: For the v6 documentation, please refer to the following pr that updates the documentation on the same behavior:
- https://github.com/sequelize/sequelize/pull/14201

2022-03-09 17:46 UTC, ephys commented
Thanks!

Could you add a small before/after example at the end of the list of breaking changes in the upgrade-to-v7 document? https://github.com/sequelize/sequelize/blob/main/docs/manual/other-topics/upgrade-to-v7.md

2022-03-09 19:00 UTC, EtienneTurc commented
I added a small example (the same as the one in the documentation) to explain the difference between the v6 and the v7 :)

2022-03-09 21:59 UTC, ephys commented on docs/manual/other-topics/upgrade-to-v7.md
> +### Merge where conditions in scope using the `and` operator
```suggestion
### `where` clauses of scopes are merged using the `and` operator
```

2022-03-09 22:02 UTC, ephys requested changes
just a few nits but lgtm!

2022-03-09 22:02 UTC, ephys commented on docs/manual/other-topics/upgrade-to-v7.md
> +  limit: 10
I've got to make the linter run on md files too

```suggestion
YourModel.addScope('scope1', {
  where: {
    firstName: 'bob',
    age: {
      [Op.gt]: 20,
    },
  },
  limit: 2,
});
YourModel.addScope('scope2', {
  where: {
    age: {
      [Op.lt]: 30,
    },
  },
  limit: 10,
```

2022-03-09 22:02 UTC, ephys commented on docs/manual/other-topics/upgrade-to-v7.md
> +Using `.scope('scope1', 'scope2')` would have yield the following WHERE clause:
```suggestion
Using `.scope('scope1', 'scope2')` would have yielded the following WHERE clause:
```

2022-03-10 08:59 UTC, EtienneTurc commented
Thanks for the review, I have done the few requested modifications :)

2022-03-10 09:13 UTC, ephys approved these changes
Looks good to me! 
Thank you for helping us improve Sequelize :)

2022-03-10 09:13 UTC, merged