docs: rework issue templates
sequelize/sequelize pull request #14431
Opened 2022-04-22 09:59 UTC by ephys

This PR reworks issue templates with the following goals:

- Emphasize that failing to provide the necessary information will result in the issue being closed.
- Emphasize that incorrectly formatted code (i.e. not using code blocks) will result in the issue being closed.
- Encourage using https://github.com/sequelize/sequelize-sscce instead of pasting incomplete code.
- Encourage people to use 👍🏼 instead of posting '+1' so we can sort by most reacted issues when prioritizing.
- Rewrite the 'are you willing to open a PR' section: it's not very useful to know that someone who isn't willing to implement the PR is able to do it. The new one conveys the message that they'll either need to do it themselves (with or without help), support financially, or wait until someone else does it

2022-04-22 10:06 UTC, WikiRik submitted a review, later dismissed
This change does make creating issues less inviting since there is much more focus on OpenCollective but I think it is for the better. Do want to hear what @sdepold thinks as well before we merge this

2022-04-22 10:09 UTC, ephys commented
Toning down the last option for "are you willing to open a PR" could be good, as long as users understand that the last checkbox means "I'm willing to wait", it doesn't need to talk about financial support

2022-04-24 13:27 UTC, fzn0x approved these changes

2022-04-24 13:31 UTC, fzn0x requested changes
Minor: follow the https://github.com/sequelize/sequelize/blob/main/README.md#book-resource text style

2022-04-24 22:05 UTC, ephys commented
@fzn0x they're good changes, I'm not reverting them, but please don't modify branches you don't own - prefer using the PR review suggestion mechanism instead :)

2022-04-24 22:06 UTC, fzn0x commented
> @fzn0x they're good changes, I'm not reverting them, but please don't modify branches you don't own - prefer using the PR review suggestion mechanism instead :)

Oops sorry! my bad

2022-05-19 16:46 UTC, sdepold commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] No, I don't have the time, I'm not contributing financially, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.
Maybe try to tone down the focus on the finance part

2022-06-02 18:51 UTC, ephys commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] No, I don't have the time, I'm not contributing financially, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.
Yes it sounds good to me

2022-06-05 15:26 UTC, WikiRik approved these changes

2022-06-05 15:27 UTC, WikiRik commented
Looks good to me now, @fzn0x do you agree?

2022-06-08 10:31 UTC, merged

2022-06-14 19:14 UTC, WikiRik commented
@ephys we forgot to update the other_issue template. do you want to work on that or shall I do that?

2022-06-14 19:31 UTC, ephys commented
I don't really know what to do with it. The issue tracker should be for docs improvements, bugs, and feature requests. "other" doesn't fit with that. Best we could do is make it clear that questions belong in discussions / slack / etc and that using that issue type will result in a transfer?

2022-06-14 20:07 UTC, WikiRik commented
That's something we could do, but I was mainly thinking of doing the same updates there as we did for the other types. So mainly adding OpenCollective and updating the responses for if people can resolve this issue themselves