feat(types): typescript 4.8 compatibility
sequelize/sequelize pull request #14990
Opened 2022-09-16 11:06 UTC by bnorbi95

### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Sequelize typings are affected in a few places by a TypeScript 4.8 breaking change (https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to).

This PR addresses #14934.

2022-09-16 12:03 UTC, fzn0x reviewed
Can you write types tests for this?

2022-09-16 16:27 UTC, WikiRik commented
Thanks for the PR!
I've gone ahead and added the new TypeScript versions to the CI in this PR. I hope you don't mind.

Are you willing to make a PR towards the main branch as well?

2022-09-17 09:43 UTC, ephys requested changes
Other than that, if tests pass (and they do), lgtm!

2022-09-17 09:43 UTC, ephys commented on src/hooks.d.ts
> +  TCreationAttributes extends {}= TAttributes
Tiny spacing issue here

```suggestion
  TCreationAttributes extends {} = TAttributes
```

2022-09-17 10:21 UTC, bnorbi95 commented on src/hooks.d.ts
> +  TCreationAttributes extends {}= TAttributes
Fixed!

2022-09-17 10:30 UTC, ephys approved these changes

2022-09-17 11:07 UTC, fzn0x approved these changes

2022-09-17 11:29 UTC, ephys commented
Failing tests are flaky tests, we can merge

2022-09-17 11:29 UTC, merged

2022-09-17 12:10 UTC, fzn0x commented
Thank you for the initiatives!