OOM in bulkCreate with bigint value
sequelize/sequelize pull request #15054
Opened 2022-09-26 11:30 UTC by gugu

## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Closes #15053 

To prevent string concatenation and keep addition correct I've added a cast to BigInt
To keep existing API result contains either number or string instead of bigint

2022-09-26 12:13 UTC, gugu commented
@ephys can I write unit test for this `formatData` instead? I think it will be much simpler and faster

2022-09-26 12:17 UTC, gugu commented
> Type of value
Sequelize returns strings for BigInts larger than Number.MAX_SAFE_INTEGER, so I tried to be consistent with that behaviour

2022-09-26 12:23 UTC, ephys commented
Unfortunately `formatResults` is an internal function specific to mysql, whereas an integration test would be able to run on all dialects (we won't ask you to fix the other dialects if they fail too). An integration test would also be more resilient to the upcoming rewrite of all query.js files

2022-09-26 12:24 UTC, ephys commented
> Sequelize returns strings for BigInts larger than Number.MAX_SAFE_INTEGER

That is true (depending on the dialect). There are a lot of inconsistencies with DataTypes but https://github.com/sequelize/sequelize/pull/14505 will finally fix all of that

2022-09-26 21:43 UTC, gugu commented
I wrote tests and changed types to match input. The test fails for SQLite, but I think it is a part of a larger problem, which is out of scope of the fix

2022-09-29 14:50 UTC, gugu commented
@ephys is there anything extra I need to change in this PR?

2022-09-30 07:54 UTC, ephys requested changes
This looks good to me, here are two minor changes in the test :)

Sorry for the delay, it's difficult to find the time to review during the work week

2022-09-30 07:54 UTC, ephys commented on test/integration/model.test.js
> +      const user = this.sequelize.define('User', {
To follow our conventions (it's not respected in old code but we're slowly refactoring everything)

```suggestion
      const User = this.sequelize.define('User', {
```

2022-09-30 07:54 UTC, ephys commented on test/integration/model.test.js
> +      if (dialectName === 'sqlite') {
```suggestion
      // sqlite returns bigints as numbers https://github.com/sequelize/sequelize/issues/11400
      if (dialectName === 'sqlite') {
```

2022-09-30 20:59 UTC, gugu reviewed
capitalize class name in test

2022-09-30 21:19 UTC, ephys approved these changes
Thanks :)

2022-09-30 21:45 UTC, merged