docs(model): Added paranoid option for Model.BelongsToMany.through
sequelize/sequelize pull request #15065
Opened 2022-09-29 13:26 UTC by ajatdarojat45

## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Because in Model.BelongsToMany.through documentation there is no paranoid option so i added it in documentation.

2022-09-29 13:38 UTC, WikiRik requested changes
Can you revert all the style changes?

2022-09-29 14:14 UTC, ajatdarojat45 commented
Hi @WikiRik thank you for reply my PR. i have changed my style changes. let me know if there are any questions

2022-09-29 14:51 UTC, ajatdarojat45 commented
i am sorry i miss it. i have changed it @WikiRik

2022-09-29 17:20 UTC, fzn0x approved these changes

2022-09-30 10:26 UTC, ephys approved these changes

2022-09-30 11:09 UTC, WikiRik approved these changes

2022-09-30 11:09 UTC, merged