adds ignoreDuplicate flag to child models for bulkCreate function
sequelize/sequelize pull request #16014
Opened 2023-05-13 05:34 UTC by viraj47

## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions? No
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository] (https://github.com/sequelize/website/)?  No documentation update
- [ ] Did you update the typescript typings accordingly (if applicable)? Not required
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?Yes
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

bulkCreate function currently only applies ignoreDuplicate flag to parent model only. if child models are inlcuded in bulkCreate and it has duplicate values then Sequlize will throw error if there is unique constraint on the child table. The PR will add ignoreDuplicate flag to child table if there is a ignoreDuplicate flag on parent table. please refer to below issue.

https://github.com/sequelize/sequelize/issues/15583

## Todos

- [ ] 
- [ ] 
- [ ]

2023-06-18 10:42 UTC, WikiRik requested changes
Can you add a test for this? See https://github.com/sequelize/sequelize/issues/11605 as well which seems to be a duplicate of the issue you are fixing

2023-06-18 11:35 UTC, viraj47 commented
> Can you add a test for this? See #11605 as well which seems to be a duplicate of the issue you are fixing
 #11605 is the exact same issue. is there guideline to adding to adding tests ?

2023-06-24 13:47 UTC, WikiRik commented
You can add an integration test under this if-block;
https://github.com/sequelize/sequelize/blob/5db695596dac4a2b366bb4793c3a2b7833f73e87/packages/core/test/integration/model/bulk-create.test.js#L432

Something like this should work, adapted from #11605 (does need some work on the expectations);
```
      it('should inherit the ignoreDuplicates options to included models', async function () {
        const data = [
          {
            username: 'John',
            Students: [{ no: 1, name: 'Sample Student Name' }],
          }, {
            username: 'Mike',
            Students: [{ no: 1, name: 'Another Student Name' }], // Student with already existing no
          },
        ];

        this.User.hasMany(this.Student);

        await this.customSequelize.sync({ force: true });

        await this.User.bulkCreate(data, { ignoreDuplicates: true, include: [this.Student] });

        const users = await this.User.findAll({ order: ['id'], include: [this.Student] });
        expect(users.length).to.equal(2);
        expect(users[0].Students.length).to.equal(1);
        expect(users[1].Students.length).to.equal(0);
      });
```

2023-06-24 13:48 UTC, WikiRik commented on packages/core/src/model.js
>              })
```suggestion
              logging: options.logging,
              ignoreDuplicates: options.ignoreDuplicates
            })
```

You can also do this instead

2024-09-08 00:14 UTC, closed without merging