fix: make `importModels` support non-default CJS exports
sequelize/sequelize pull request #16844
Opened 2023-12-07 07:36 UTC by ckvv

Fixes #16843

2023-12-12 08:48 UTC, ephys commented
Could you add a unit test that tries to import a CJS file with "named" exports? This should cover what is added in this PR

You can do that in `import-models.test.ts`

2023-12-12 08:48 UTC, ephys requested changes

2023-12-12 08:48 UTC, ephys commented on packages/core/src/import-models.ts
> +    Object.assign(module, module.default);
modules are typically sealed, so you need to create a copy like below:

![image](https://github.com/sequelize/sequelize/assets/1280915/6d44a317-a6e6-4df1-b835-d30c4b5ae991)

```suggestion
    module = { ...module, ...module.default };
```

2023-12-12 08:48 UTC, ephys commented on packages/core/src/import-models.ts
> +  if (module.default && !isModelStatic(module.default) && typeof module.default === 'object') {
Adding some info for future maintainers

```suggestion
  // when importing a CJS file, sometimes only the default export is available, as named exports depend on the file's exports being statically analyzable by node. The default exports contains the contents of the file's `module.exports`
  if (module.default && !isModelStatic(module.default) && typeof module.default === 'object') {
```

2024-02-02 21:18 UTC, ephys commented
Made a tiny change to only spread plain objects (objects with either no prototype, or `Object.prototype` as the prototype). If the default export is a class, or a date, etc, we should not spread it

2024-02-02 21:25 UTC, WikiRik approved these changes

2024-02-02 21:53 UTC, merged