feat(ibmi): add database version compatibility check for native boolean + initial unit tests
sequelize/sequelize pull request #16909
Opened 2023-12-29 05:27 UTC by rcronin

## Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Added a check within data-types.js for the IBM i dialect to check the database version. If it's the latest known version, it implements the base boolean support, which handles booleans properly within javascript and back to the database. Also copied the DB2 unit tests as a start for IBM i unit testing.

## Todos

2023-12-29 19:07 UTC, WikiRik commented
Don't worry about the failing artifact download actions, that's a known flaky thing in the new version of the action. I can just rerun the checks if needed but you should be good if unit tests pass.

2023-12-29 21:17 UTC, rcronin commented
@WikiRik sounds good. This is ready to review

2024-01-16 22:03 UTC, rcronin commented
@WikiRik - any update on when this may get reviewed/merged?

2024-01-31 15:54 UTC, WikiRik reviewed
Could you add some unit tests that simulate ibmi 7.5.0 (or higher)? You can just do something similar as here;
https://github.com/sequelize/sequelize/blob/6800fbddfa9da8d781a1d3fdc2f611d226e9e8e4/packages/core/test/unit/query-interface/create-table.test.ts#L13-L66

2024-01-31 15:54 UTC, WikiRik commented on packages/core/src/dialects/ibmi/data-types.ts
> +    return databaseVersion >= 7.5;
We can use the `gt` function from [semver](https://www.npmjs.com/package/semver) to compare this to getDatabaseVersion()

2024-01-31 15:54 UTC, WikiRik commented on packages/core/test/config/config.ts
> +    databaseVersion: '7.3.0',
```suggestion
```
ibmi has a defaultVersion of 7.3.0 already

2024-01-31 15:54 UTC, WikiRik commented on packages/core/test/unit/query-interface/bulk-insert.test.ts
> +      ibmi: toMatchRegex(/^INSERT INTO "Users" \("firstName"\) VALUES (?:\('\w+'\),){999}\('\w+'\)$/),
I believe that the custom expectations in the other changed tests can be removed

2024-02-11 17:11 UTC, ephys requested changes

2024-02-11 17:11 UTC, ephys commented on packages/core/src/dialects/ibmi/data-types.ts
> +  protected supportsNativeBooleans() {
this should be hard private

2024-02-11 17:11 UTC, ephys commented on packages/core/src/dialects/ibmi/data-types.ts
> +      = Number.parseFloat(this._getDialect().sequelize.options.databaseVersion || this._getDialect().defaultVersion);
Don't get the database version like this, but via `sequelize.getDatabaseVersion()`

2024-02-11 17:11 UTC, ephys commented on packages/core/src/dialects/ibmi/query-generator.js
> -      query = `SELECT * FROM FINAL TABLE (${query})`;
why remove the "select from final table"? :o

2024-02-11 17:13 UTC, ephys commented on packages/core/test/unit/dialects/ibmi/query-generator.test.js
The functions being tested in this new file already have common test files, so I don't want to approve this file. The new tests should be added to the new files instead, if they're relevant

2024-04-17 18:59 UTC, rcronin commented
Finally circling back to this. To implement with the dialect being split out, how should I approach this pull request? Throw out and redo it?

2025-02-08 12:05 UTC, closed without merging