fix(types): incorrect type for default in findOrCreate and findOrBuild
sequelize/sequelize pull request #16948
Opened 2024-01-12 10:02 UTC by MaksymAleieiv

## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Closes [#16947](https://github.com/sequelize/sequelize/issues/16947)
Fixed incorrect types for `default` in `Model.findOrCreate` and `Model.findOrBuild`

## Todos

N/a

2024-01-12 10:22 UTC, WikiRik reviewed
Change looks good to me. Can you add a typing test for this?

Feel free to open another PR with this change towards the v6 branch so this can be added in the next release as well. We use the main branch for the v7 alphas

2024-01-12 17:17 UTC, MaksymAleieiv commented
I added type tests and better types for findOrCreate({ raw: true }), now if it finds row it returns raw values with correct type
![image](https://github.com/sequelize/sequelize/assets/89811231/9ba4d757-4341-49c5-b309-86a945ff7b1d)

After you approve these changes I will also create a PR for v6. 

PS. If you are going to release another v6 can you integrate fix for [wrong generic type for changed()](https://github.com/sequelize/sequelize/pull/16047) there too please ?

2024-02-02 21:28 UTC, ephys requested changes

2024-02-02 21:28 UTC, ephys commented on packages/core/src/model.d.ts
> +  defaults?: Partial<TCreationAttributes>;
Creation attributes are already partial, but only those that can be omitted as declared in the model.

2024-02-09 09:13 UTC, closed without merging